### ISSUE TITLE
FAILED_A2A_LOGIN

### ISSUE THREAD

**Issue by cyq7on** [line/line-sdk-starter-android#14]
I have been logined successfully by web ,but failed by line app,I'm confused.

**Comment by royl2k90** [comment]
what have u done so far? u import the whole project and run it?

**Comment by cyq7on** [comment]
Yeah,there are no problems logining by web.

**Comment by royl2k90** [comment]
by web, you mean the line app from chrome browser extension or the line app from windows 10 store?

**Comment by cyq7on** [comment]
There 2 ways of logining."The LINE SDK for Android automatically determines whether LINE is installed on the user’s device. If LINE is installed, the SDK delegates the login process to LINE. If not, the SDK will display the login screen and authenticate the user using the user’s email address and password."I llogined successfully by the latter.

**Comment by cyq7on** [comment]
There are 2 ways of logining."The LINE SDK for Android automatically determines whether LINE is installed on the user’s device. If LINE is installed, the SDK delegates the login process to LINE. If not, the SDK will display the login screen and authenticate the user using the user’s email address and password."I logined successfully by the latter.

**Comment by mvn-vinhhuynh-dn** [comment]
https://github.com/line/line-sdk-starter-android/issues/14#issue-158652947 
I got same error with you ❓

**Comment by cyq7on** [comment]
Let's share.

**Comment by mvn-vinhhuynh-dn** [comment]
I didn't resolve it.

**Comment by at-chauhoang** [comment]
I got same error and I did not found to fix it So I used this method to login 
authManager.loginByAccount(Activity activity) -->It always login by web whether LINE APP is installed or not.It is a temporary solution.

**Comment by cyq7on** [comment]
yeah,I know the method,3q.

**Comment by at-chauhoang** [comment]
Did you resolve it ?

**Comment by cyq7on** [comment]
Not yet,I have no idea.Hoping line to give a solution!

**Comment by at-chauhoang** [comment]
No reply from line.

**Comment by cyq7on** [comment]
Me too.

**Comment by GuitarSucks** [comment]
Hi guys,

First I would like to remind that we don't provide technical support for LINE Login. So any answers provided here is our best effort to help you guys. So it will be grateful for your understanding and hope other members help each other.

Anyways, there is not much information other than you can login by web (It will be great if you post the error message). The app to app authentication relies on confirming if the application requesting authorization has the correct credentials, meaning that if the SHA1 signature of your application doesn't match it will fail.

Here are the common reasons:
- Have not set the package name and package signature on Developers site
- The package signature of the application is incorrect
- The package name is incorrect

**Comment by cyq7on** [comment]
Yeah,I know that ,I have checked it,and because I can login by web,I don't think the common reasons are suitable for me,right?

**Comment by GuitarSucks** [comment]
Can you check if the user you are logged in to the LINE App is registered on your Channel's role?

**Comment by at-chauhoang** [comment]
@GuitarSucks  
Thank you for support. I found reason.

**Comment by cyq7on** [comment]
The user is me,who are the developer role,it's OK?

**Comment by royl2k90** [comment]
I can login by LINE app and display my name and profile picture. I tested their sample project on Android Studio instead of Eclipse.

**Comment by royl2k90** [comment]
If you have Teamviewer, I can try to remotely help you.

**Comment by royl2k90** [comment]
<iframe src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fplayok.sp33dcub3r%2Fvideos%2F10206747177973879%2F&show_text=1&width=560" width="560" height="400" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>

**Comment by cyq7on** [comment]
OK,3q.Now I am in my hometown,I'll contact with you later.

**Comment by royl2k90** [comment]
How can I contact you online? I am free during the weekends.

**Comment by cyq7on** [comment]
Facebook,wechat,and QQ is what I am using.How about you?

**Comment by royl2k90** [comment]
WhatsApp, LINE, Facebook. How can I search you on Facebook?

**Comment by royl2k90** [comment]
I posted my demo video on my Facebook. Add me so you can see it.

**Comment by at-chauhoang** [comment]
@cyq7on 
Do you try checking the package name is correct ?

**Comment by cyq7on** [comment]
Yeah,it's right

**Comment by cyq7on** [comment]
This is my facebook,cyq7on@qq.com.May you tell me yours.I am trouble in network.

**Comment by royl2k90** [comment]
Search on Facebook
98998965

**Comment by cyq7on** [comment]
Ok,3q.

**Comment by kenshinzz** [comment]
@cyq7on 

I have trouble too  if u found solution please tell me ,This is my facebook

https://www.facebook.com/daiguren.hyourinmaru.5

**Comment by royl2k90** [comment]
i send you a message in Facebook, go to my profile, I upload a video how to login LINE from the sample app

**Comment by cyq7on** [comment]
OK,3q.When I come back to school,I'll take it.

**Comment by royl2k90** [comment]
https://www.facebook.com/playok.sp33dcub3r

**Comment by GuitarSucks** [comment]
Hi,
Glad to see everyone is helping each other.
I have a recommendation about posting an error. Please try to get the message error as below.

`public void loginComplete(LineLoginFuture future) {logger.info("Login error! " + future.getCause().getMessage());}
`
Could provide some more information about the error.

**Comment by royl2k90** [comment]
Also, please remove all the semi-colons ":" from your app signature when you copy and paste.

**Comment by cyq7on** [comment]
@royl2k90 I have sent a request on Facebook and watched the video,you're successful! Now I can just  use exclusive method to find the reason.May you use the app what I used to get the signature and compare with yours?https://res.wx.qq.com/open/zh_CN/htmledition/res/dev/download/sdk/Gen_Signature_Android2.apk

**Comment by royl2k90** [comment]
I have problem accepting the request. Could u send me again? Then message me on Facebook so I can accept it.

**Comment by royl2k90** [comment]
So the problem is solved. You shoud not use third-party apps to get the package signature of your running application. Instead you have to cd to the keytool.exe command at JDK bin folder, then run the following command to get the SHA1 signature.

`keytool -list -v -keystore "the directory where your debug.keystore file is"`

An example is:
`keytool -list -v -keystore "C:\Users\RoyLin\.android\debug.keystore"`

Then key in the default password "android" without quotes.

Please do not share your signatures around.

Your debug.keystore file is found in your home directory and in the .android folder. once you have the SHA1 signature, remove the semi-colons (:) and paste it into Android Package Signature of LINE channel console.

**Comment by cyq7on** [comment]
Yeah,the reason and the solution is described by royl2k90,thanks very much .Also,thanks everybody!

**Comment by DanteAndroid** [comment]
Actually, I confirmed the signature (Which I use command to get), it's correct, and I still get this error.
`error=FAILED_A2A_LOGIN, errorCode=2`

**Comment by cyq7on** [comment]
Account is also import if you don't make the app Basic information to be PUBLISHED,[this is my summary,but it's Chinese.](http://blog.csdn.net/cyq7on/article/details/51684442)

**Comment by DanteAndroid** [comment]
@cyq7on 谢谢。但是我检查了签名、roles也加入了开发者账号、information的配置都是对的，依然无法用客户端登录。我怀疑是不是最新的sdk出了问题

**Comment by cyq7on** [comment]
那你换一个低版本的试试？

**Comment by DanteAndroid** [comment]
没有低版本的。也有可能是我刚刚加入developer账号要等一段时间。但是CHANNEL_EDITOR按理来说也应该可以登录的呀。你用的是哪个账号登录的？

**Comment by cyq7on** [comment]
就是申请者的line账号

**Comment by DanteAndroid** [comment]
没有自己额外添加developer么

**Comment by cyq7on** [comment]
申请者的是立即就可以登录的，其他的会存在延时，但延时也不久，当时我就这个情况。

**Comment by DanteAndroid** [comment]
@GuitarSucks I checked everything here(spending days to it), still fail to login with client. What can I do now?

**Comment by liyinzoe** [comment]
@DanteAndroid
The package signature value is the SHA1 value above without “:”. In this case, the package signature is:
5057B0B9A325EEE5A254198531325263491C2580
my problem like this ....
you can check it

**Comment by DanteAndroid** [comment]
@liyinzoe That's not my problem. I recreate a line account, then it works. The cause of that problem before is never found.

**Comment by DanteAndroid** [comment]
Hey, guys, sorry to bother, but is there any ShareSDK for Line? @cyq7on

**Comment by cyq7on** [comment]
Not found at the moment.
